### ISSUE TITLE
Pin neovim version

### ISSUE THREAD

**Issue by NotAShelf** [NotAShelf/nvf#206]
Currently we're using neovim-unwrapped from nixos-unstable, which may change inbetween nixpkgs input bumps, or for those overriding the nixpkgs input.

I propose that we get the neovim-unwrapped package from the neovim repository directly, using the flake they provide in the contrib directory, allowing us to pin the branch directly as follows:

```nix
# ...

inputs.neovim-unwrapped.url = "github:neovim/neovim/v0.9.5?dir=contrib";

# ...
```

and also allows users to do so at their own peril. 

Overriding the package has been made easier already through the help of the customizable package option that I've added recently, but I do like the idea of making the input customizable also.

CC @FrothyMarrow and @horriblename for feedback.

**Comment by horriblename** [comment]
seems like a good change, no objections.

**Comment by FrothyMarrow** [comment]
Same here, sounds like a good idea.
