### ISSUE TITLE
Custom binds show up in the command prompt before getting executed

### ISSUE THREAD

**Issue by justchokingaround** [NotAShelf/nvf#243]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### 👟 Reproduction steps

Spam a custom bind and you will see that for a very short period of time you get a command popup, before it gets executed.

### 👀 Expected behavior

I should not see that

### 😓 Actual Behavior

![image](https://github.com/NotAShelf/neovim-flake/assets/44473782/f0d5440f-dc8d-4619-8c8d-09621f5c75f2)
This is for the following bind:
```nix
            "<Esc>".action = ":noh<CR>";
```

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.6.23, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.18.2`  - nixpkgs: `/etc/nix/inputs/nixpkgs`

### 📝 Relevant log output

```bash
nop
```

**Comment by FrothyMarrow** [comment]
@justchokingaround By default the mappings are not silent. You can set `vim.maps.<key>.silent` to `true` and it will not appear in the command line.

In you case, it will be the following:
```nix
vim.maps.normal = {
    "<Esc>" = {
        action = ":noh<CR>";
        silent = true;
    };
};
```

This is intended behaviour, you can find the related docs with `:help :map-silent` in Neovim.

**Comment by justchokingaround** [comment]
oki, thank you a lot!
