### ISSUE TITLE
Code does not reflect documentation regarding `programs.nvf`

### ISSUE THREAD

**Issue by Nowaaru** [NotAShelf/nvf#279]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

In the `main` and `v0.6` branch, [the code](https://github.com/NotAShelf/nvf/blob/5b982fafa07b449299ce9898f0f9a7a0f8b75bb4/flake/modules/home-manager.nix#L14C1-L24C21) describes "`programs.neovim-flake`" whereas the documentation describes "`programs.nvf`"

<details>
<summary>screenshot (lightmode zzz)</summary>

![image](https://github.com/NotAShelf/nvf/assets/16274568/dd4eb992-9e99-4567-81fa-a6677f925e25)

</details>

### 👟 Reproduction steps

N/A

### 👀 Expected behavior

A warning trace appearing when attempting to index `neovim-flake` before redirecting to `programs.nvf`.  

### 😓 Actual Behavior

`error: The option 'programs.nvf' does not exist.`

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.6.29, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.21.2`  - nixpkgs: `/nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source`

### 📝 Relevant log output

```bash
error: The option `programs.nvf' does not exist. Definition values:
       - In `/nix/store/aafrhbikr2p3mz3zazhx89br0whaf1g9-source/usr/dev/vim.nix':
           {
             enable = true;
             settings = { };
           }
```

**Comment by NotAShelf** [comment]
Thanks for reporting this, I somehow managed to skip renaming NixOS and Home-Manager modules while I was going through renaming the project.

Pushed a quick patch to the `rename-module-opts` branch, #280 will have the details. Would you be able to test the `rename-module-opts` branch and tell me if it works as intended?

**Comment by Nowaaru** [comment]
Getting a 'renaming error' when indexing `programs.nvf` though I never index `neovim-flake`. Trace is attached.
[hm.log](https://github.com/NotAShelf/nvf/files/15210181/hm.log)

**Comment by NotAShelf** [comment]
Minor mistake on my behalf, could you try again please?

**Comment by Nowaaru** [comment]
Looks good. Good stuff, Shelf-man. 👍

**Comment by NotAShelf** [comment]
Thank you for testing :)
