### ISSUE TITLE
Enabling colorizer.sass breaks generally everything.

### ISSUE THREAD

**Issue by Nowaaru** [NotAShelf/nvf#282]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

Enabling colorizer.sass breaks NvimTree, Fidget, WhichKey, LspSaga, and whatever else depending on which loads before what.

![image](https://github.com/NotAShelf/nvf/assets/16274568/19e5e3d7-3b6c-42cd-b3bc-82e834bad28b)

### 👟 Reproduction steps

Enable colorizer.sass.

### 👀 Expected behavior

Not this.

### 😓 Actual Behavior

I can't use 90% of my plugins.

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.6.29, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.21.2`  - nixpkgs: `/nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source`

### 📝 Relevant log output

```bash
E5108: Error executing lua .../myNeovimPackages/start/which-key/lua/which-key/view.lua:79: FileType Autocommands for "*": Vim(append):Error executing lua callback: ...eovimPackages/start/nvim-colorizer-lua/lua/colorizer.lua:228: attempt to index field 'sass' (a boolean value)
```

**Comment by NotAShelf** [comment]
This was closed automatically by #283 being merged. Feel free to re-open if the issue persists.
