### ISSUE TITLE
vim.maps rewrite

### ISSUE THREAD

**Issue by diniamo** [NotAShelf/nvf#304]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

Other

### 🔖 Feature description

The current implementation isn't great, because the implementation is messy, and it's not flexible, since the user can't specify modes.

### ✔️ Solution

My suggestion is very similar to the previous one, except binds are directly in `vim.maps` and there is a new mode attribute in their definition, eg.:
```nix
vim.maps."..." = {
  mode = "n";
  action = "...";
};
```
(mode is of type `either str (listOf str)`)

### 📝 Additional Context

This would still allow the user to have a very similar structure, eg.:
```nix
vim.maps = builtins.mapAttrs (_: value: { mode = "n"; } // value) {
  "...".action = "...";
}
```

**Comment by ppenguin** [comment]
It would be cool if `mode` would be a string that allows multiple modes, such as `modes = "niv"` for `normal`, `insert`, `visual`. I believe I've used something similar before in `nixvim` and the UX is much better than having to inherit functions from lib and use e.g. `vim.maps.normal = lib.mkMerge [ (mkBinding ....) ... ];` and then the same for other maps.

**Comment by horriblename** [comment]
something like this maybe?

```nix
vim.maps = {
  "<leader>x" = [
    {mode = ["n", "v"]; action = ":foo<CR>";}
    {mode = "i"; action = "<cmd>bar<cr>";}
  ];
  
  "<leader>y" = {mode = "c"; action = "...";}
};
```

**Comment by NotAShelf** [comment]
> `["n", "v"]` ah yes, the infamous comma in a Nix list...

**Comment by diniamo** [comment]
> something like this maybe?
> 
> ```nix
> vim.maps = {
>   "<leader>x" = [
>     {mode = ["n", "v"]; action = ":foo<CR>";}
>     {mode = "i"; action = "<cmd>bar<cr>";}
>   ];
>   
>   "<leader>y" = {mode = "c"; action = "...";}
> };
> ```

wtf am I looking at

**Comment by diniamo** [comment]
@ppenguin I'm pretty sure there is a map mode whose short form is 2 characters, and besides, a list makes more sense, as that's used in the lua api too.

**Comment by horriblename** [comment]
heh I misread

**Comment by horriblename** [comment]
though the current rewrite has the problem of not being able to make different bindings for the same key on different modes (what I suggested)

that aside, string (e.g. "nvc" for normal + visual + command) mode should work with this

**Comment by diniamo** [comment]
Make vim.maps a list then, idk

**Comment by diniamo** [comment]
#352 #360
