### ISSUE TITLE
Support tiny-devicons-auto-colors.nvim

### ISSUE THREAD

**Issue by uncenter** [NotAShelf/nvf#307]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

Support for https://github.com/rachartier/tiny-devicons-auto-colors.nvim built in, seeing as https://github.com/nvim-tree/nvim-web-devicons is already built in it would fit in well. 

### ✔️ Solution

Could be under `settings.vim.visuals.tinyDeviconsAutoColors` or could just be enabled by default through `settings.vim.theme` which would update the palette for the enabled theme.

**Comment by NotAShelf** [comment]
This has been on my to-do list for a while now. Though, I'm currently on vacation and might not be able to take a look at the end of this week. If you'd like to make a PR, feel free. Otherwise I'll be working on this after thursday.

**Comment by NotAShelf** [comment]
Sorry it took me this long, I have been constantly distracted by other things. Added in #451
