### ISSUE TITLE
Set undofile from the module

### ISSUE THREAD

**Issue by Soliprem** [NotAShelf/nvf#331]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

Other

### 🔖 Feature description

As asked and described in the discord, a way to set the undofile option

### ✔️ Solution

-

### ❓ Alternatives

A possible alternative is making a general "option" module option that passes the string to neovim as a vim.o.<option>, or something similar

**Comment by NotAShelf** [comment]
I'll add this later today.

**Comment by NotAShelf** [comment]
Sorry for the delay @Soliprem, I have been absent in development for a while due to IRL events.

Could you see if #367 resolves your issue and if it works as intended?
