### ISSUE TITLE
Fails to build when Typst is enabled

### ISSUE THREAD

**Issue by Soliprem** [NotAShelf/nvf#357]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

TItle

### 👟 Reproduction steps

Enable Typst, try rebuild

### 👀 Expected behavior

Should rebuild

### 😓 Actual Behavior

Is failing

### 💻 Metadata

fetching path input 'path:/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source' these 6 paths will be fetched (0.76 MiB download, 10.21 MiB unpacked):   /nix/store/rnndls2fiid1sic81i06dkqjhh24lpvr-file-5.45   /nix/store/ndqb245cd71hjaggrrlhfmwvflsc7jih-gnu-config-2024-01-01   /nix/store/70anjdzz5rj9lcamll62lvp5ib3yqzzr-gnumake-4.4.1   /nix/store/dv5vgsw8naxnkcc88x78vprbnn1pp44y-patchelf-0.15.0   /nix/store/1r32fki5z5ivgaikgh8pq0r6vz3b0jpj-stdenv-linux   /nix/store/i4iynx9axbq23sd0gyrc5wdb46zz6z8l-update-autotools-gnu-config-scripts-hook copying path '/nix/store/ndqb245cd71hjaggrrlhfmwvflsc7jih-gnu-config-2024-01-01' from 'https://cache.nixos.org'... copying path '/nix/store/rnndls2fiid1sic81i06dkqjhh24lpvr-file-5.45' from 'https://cache.nixos.org'... copying path '/nix/store/70anjdzz5rj9lcamll62lvp5ib3yqzzr-gnumake-4.4.1' from 'https://cache.nixos.org'... copying path '/nix/store/dv5vgsw8naxnkcc88x78vprbnn1pp44y-patchelf-0.15.0' from 'https://cache.nixos.org'... copying path '/nix/store/i4iynx9axbq23sd0gyrc5wdb46zz6z8l-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'... copying path '/nix/store/1r32fki5z5ivgaikgh8pq0r6vz3b0jpj-stdenv-linux' from 'https://cache.nixos.org'...  - system: `"x86_64-linux"`  - host os: `Linux 6.6.44, NixOS, 24.11 (Vicuna), 24.11.20240804.cb9a96f`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Lix, like Nix) 2.90.0-rc1`  - channels(root): `"home-manager, nixos"`  - nixpkgs: `/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source`

### 📝 Relevant log output

```bash
error: builder for '/nix/store/s82wg453h4rynw1kk2s89kqz4890mp34-typst-lsp-0.13.0.drv' failed with exit code 101;
       last 25 log lines:
       >    |
       > 83 |     let items: Box<_> = format_items
       >    |              ++++++++
       >
       >    Compiling num-bigint v0.4.4
       >    Compiling half v2.4.0
       >    Compiling xmlwriter v0.1.0
       >    Compiling httparse v1.8.0
       >    Compiling ciborium-io v0.2.2
       >    Compiling pico-args v0.5.0
       >    Compiling jpeg-decoder v0.3.1
       >    Compiling rayon-core v1.12.1
       >    Compiling linked-hash-map v0.5.6
       >    Compiling icu_locid_transform_data v1.4.0
       >    Compiling ciborium-ll v0.2.2
       >    Compiling phf_generator v0.11.2
       >    Compiling crossbeam-deque v0.8.5
       >    Compiling yaml-rust v0.4.5
       >    Compiling fancy-regex v0.11.0
       >    Compiling gif v0.13.1
       >    Compiling num-integer v0.1.46
       >    Compiling stacker v0.1.15
       > For more information about this error, try `rustc --explain E0282`.
       > error: could not compile `time` (lib) due to 1 previous error
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/s82wg453h4rynw1kk2s89kqz4890mp34-typst-lsp-0.13.0.drv'.
error: 1 dependencies of derivation '/nix/store/g5ql25qij2c10vcwwzyjq9zq1iwkih5l-init.lua.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qlqy6qdj1dyvjwl0r3kscxim44lm6jyg-nvf-init.lua.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nc6spxr64211lp2mvamxv4c92r2afsq9-init.lua.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fdh7vfs1x1d8dv33m31jcl9gh11nsdnc-nvf-print-config-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2j1v5f53r293zxg8x5hrfi38pc380617-nvf-with-helpers.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d4lxs2kjnjr9w1zdjw0zi7csqgyj33qp-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l0zbwm52y4smlzy2s718ga2dwc77vkj4-home-manager-generation.drv' failed to build
```

**Comment by horriblename** [comment]
Many other rust programs fail to build for me on latest nixpkgs so probably not our fault, but @NotAShelf may know more

**Comment by NotAShelf** [comment]
The rust compiler bump in nixpkgs broke a ton of packages. There is nothing we can do other than to wait.

Users may un-follow nixpkgs for nvf, or pin nixpkgs to an older revison.

**Comment by NotAShelf** [comment]
Relevant PRs & issues:

- `https://github.com/NixOS/nixpkgs/pull/335263`
   - `https://github.com/nvarner/typst-lsp/pull/515`
- `https://github.com/NixOS/nixpkgs/issues/332957`

Pinning nixpkgs to a pre-staging branch currently seems like the best option. I will update nvf's nixpkgs branch, but those overriding nixpkgs will have to do so on their own (or unfollow.)

**Comment by NotAShelf** [comment]
This has been fixed in nixpkgs and is already propagated to the unstable channel. I've updated nvf's own nixpkgs input, so it should work for both `follow`ed and non-`follow`ed inputs.

Closing.
