### ISSUE TITLE
Statusline Theme

### ISSUE THREAD

**Issue by C4E5G3** [NotAShelf/nvf#392]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

Would it be possible to add the "powerline_dark" theme to the available statusline themes? 

### ✔️ Solution

I could use powerline_dark rather then powerline

**Comment by NotAShelf** [comment]
Could you test #393 for me? The PR adds `powerline_dark` as an available theme.

**Comment by C4E5G3** [comment]
![Capture d’écran du 2024-09-30 23-42-26](https://github.com/user-attachments/assets/cf71ebee-0c38-49b3-8956-194d13811dff)

Seems pretty good to me Raf!!
