### ISSUE TITLE
Embeded link to docs in readme is broken.

### ISSUE THREAD

**Issue by ShadowReaper420** [NotAShelf/nvf#394]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

The embed in documentation for the nvf manual is broken and doesn't link anywhere.

### 👟 Reproduction steps

Scroll down in readme

### 👀 Expected behavior

A link to the nvf manual to be present

### 😓 Actual Behavior

There's no link.

### 💻 Metadata

No.

### 📝 Relevant log output

```bash
https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

**Comment by NotAShelf** [comment]
https://github.com/NotAShelf/nvf/commit/7417c6e4f382f847f841db84c6cb26bcb82716de


Thanks for the report.
