### ISSUE TITLE
Stylix

### ISSUE THREAD

**Issue by KamWithK** [NotAShelf/nvf#427]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

[Stylix](https://github.com/danth/stylix) is a NixOS module which applies colour schemes and fonts to a range of applications including NeoVim. However, as nvf doesn't set itself as `programs.neovim` (afaik) Stylix's [automatically installed plugin](https://github.com/danth/stylix/blob/master/modules/neovim/hm.nix) isn't installed/loaded.

### ✔️ Solution

Would it be possible to somehow add support for Stylix in nvf? Maybe through the [pre-existing plugin](https://github.com/danth/stylix/blob/master/modules/neovim/hm.nix) or maybe this [alternative approach](https://github.com/sodiboo/niri-flake/blob/main/stylix.nix) would be cleaner?

### 📝 Additional Context

Just curious to try out nvf and see if it can work with Stylix, sorry if there is an obvious way to do this I haven't thought off

**Comment by NotAShelf** [comment]
I'm not fond of (nor very familiar= with Stylix, so I cannot give you a precise answer without having looked into the codebase.

If Stylix has a way to expose a base16 palette, you may use the Base16 feature added to nvf in v0.7 (dev branch). Alternatively, if Stylix has a way to access the Neovim plugin as a package directly you can get the package and add it to `programs.nvf.startPlugins` to make it available to nvf.

**Comment by diniamo** [comment]
It''s already "supported" on the v0.7 branch. You can pass the attribute set with the colors to the base16 theme.

**Comment by Soliprem** [comment]
adding an inherit exposes the 16-color palette that stylix generates:

```nix
{
...
}: let
  inherit (config.lib.stylix) colors;
in {
...
}
```

**Comment by KamWithK** [comment]
> I'm not fond of (nor very familiar) with Stylix, so I cannot give you a precise answer without having looked into the codebase.

I'm curious why you don't like Stylix?

> Though if Stylix has a way to expose a base16 palette, you may use the Base16 feature added to nvf in v0.7 (dev branch). Alternatively, if Stylix has a way to access the Neovim plugin as a package directly you can get the package and add it to `programs.nvf.startPlugins` to make it available to nvf.

I guess the nvf Base16 feature is my best bet by the sounds of things

**Comment by KamWithK** [comment]
> I'm not fond of (nor very familiar) with Stylix, so I cannot give you a precise answer without having looked into the codebase.
> 
> Though if Stylix has a way to expose a base16 palette, you may use the Base16 feature added to nvf in v0.7 (dev branch). Alternatively, if Stylix has a way to access the Neovim plugin as a package directly you can get the package and add it to `programs.nvf.startPlugins` to make it available to nvf.

I can't really find the docs for this base16 feature, would you be able to link me to it?

**Comment by Soliprem** [comment]
@KamWithK I just tried this in my config (I pin the 0.7 branch) and it works. Though keep in mind that often stylix generated themes aren't the best for readability, if you use it for generation.

```nix
{
...
}: let
  inherit (config.lib.stylix) colors;
in {
programs.nvf.settings.vim = {
...
        theme = {
          enable = true;
          name = "base16";
          style = "dark";
          base16-colors = {
            inherit (colors) base00 base01 base02 base03 base04 base05 base06 base07;
            inherit (colors) base08 base09 base0A base0B base0C base0D base0E base0F;
          };
          transparent = false;
        };

};
}
```
I don't know if there's a cleaner way to do it, but this is what I cobbled together quickly :)

**Comment by bloxx12** [comment]
```nix
{
...
}: let
  inherit (config.lib.stylix) colors;
in {
programs.nvf.settings.vim = {
...
        theme = {
          enable = true;
          name = "base16";
          style = "dark";
          base16-colors = colors;
          transparent = false;
        };
...
};
}
```
should suffice I think

**Comment by KamWithK** [comment]
> @KamWithK I just tried this in my config (I pin the 0.7 branch) and it works. Though keep in mind that often stylix generated themes aren't the best for readability, if you use it for generation.
> 
> ```nix
> {
> ...
> }: let
>   inherit (config.lib.stylix) colors;
> in {
> programs.nvf.settings.vim = {
> ...
>         theme = {
>           enable = true;
>           name = "base16";
>           style = "dark";
>           base16-colors = {
>             inherit (colors) base00 base01 base02 base03 base04 base05 base06 base07;
>             inherit (colors) base08 base09 base0A base0B base0C base0D base0E base0F;
>           };
>           transparent = false;
>         };
> ...
> };
> }
> ```
> 
> I don't know if there's a cleaner way to do it, but this is what I cobbled together quickly :)

Oh wow I saw your reply literally after I figured out around the same thing as you ahahaha

**Comment by KamWithK** [comment]
> @KamWithK I just tried this in my config (I pin the 0.7 branch) and it works.

Yeah I updated my flake to use `github:notashelf/nvf/v0.7`

> Though keep in mind that often stylix generated themes aren't the best for readability, if you use it for generation.

I don't use it to generate I just use it so everything on my computer uses the exact same theme which I only have to set in one place, which is very nice in comparison to trying to set every applications theme up separately

**Comment by Soliprem** [comment]
> 
       error: The option `vim.theme.base16-colors.__functor' does not exist. Definition values:
       - In `<unknown-file>': <function>
       
When I tried with simply `colors` I got the same error, and it was fixed by specifying the imported attributes. I assume the reason might be because there's a bunch of other things being exposed by the import, but I can't be sure without looking into it
