### ISSUE TITLE
Add typst-preview.nvim

### ISSUE THREAD

**Issue by deviantsemicolon** [NotAShelf/nvf#429]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

Add typst-preview.nvim, which allows for live updating of typst documents. This would make it much more convenient to use

### ✔️ Solution

What it says on the tin

### ❓ Alternatives

Not using preview would be very annoying. If this is too much trouble, I could add it as a custom plugin

### 📝 Additional Context

🥺

**Comment by NotAShelf** [comment]
I'm going to add this somewhat soon, but I'd like to avoid cramping any more plugins to 0.7 to make sure the release may happen in time. This will probably be after I merge 0.7.

**Comment by Soliprem** [comment]
#490 completes?
