### ISSUE TITLE
precognition.nvim

### ISSUE THREAD

**Issue by Nowaaru** [NotAShelf/nvf#434]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

As much as I use vim, I frequently mix up my motions or sometimes forget more efficient ones exist. Being able to quickly glance at motions would help regardless of aptitude.

### ✔️ Solution

It would be nice to have a plugin that shows what motions are available. This helps that.

### ❓ Alternatives

There aren't any other alternatives worth looking at as far as I know.

### 📝 Additional Context

https://www.reddit.com/r/neovim/comments/1g2a78u/precognition_v11_learning_motions_made_easyier/
https://github.com/tris203/precognition.nvim

If possible, I would like to take a gander at this myself for the v0.7 release.

**Comment by NotAShelf** [comment]
Seems like a useful plugin to have, by all means feel free to PR it in.

**Comment by NotAShelf** [comment]
Fixed by #437
