### ISSUE TITLE
Nix newbie question... default configuration?

### ISSUE THREAD

**Issue by cratedev** [NotAShelf/nvf#435]
Hey, sorry for wasting anyone's time because this is probably more realistically a Nix question rather than about this flake, but I'm a little lost.

When I run
`nix run github:notashelf/nvf`

nvim looks and acts exactly how I want as a starting point. It's fantastic.

But when I install it, I don't know how/where to put a configuration, and my nvim seems stock.

In my flake.nix:

```
inputs = {
...
    nvf = {
        url = "github:notashelf/nvf";
        inputs.nixpkgs.follows = "nixpkgs";
    };
};
```

In my configuration (home/programs/nvf/default.nix) I have:
```
{ inputs, ... }:
{
  imports = [
	inputs.nvf.homeManagerModules.default
  ];
  programs.nvf = {
    enable = true;
  };
}
```

I just don't know where to go from here. I'm clearly missing the "default" config, but I'm not sure how I could be missing something that's default. Any tips for a newb?

**Comment by Nowaaru** [comment]
This is what my configuration for nvf looks like:
```nix
{
  inputs,
  pkgs,
  ...
}: {
  imports = [inputs.nvf.homeManagerModules.default];

  programs.nvf = {
    enable = true;
    settings.vim = {}; /* ... config goes here  */
  };
}
```

You can see the definition in [`flake/modules/home-manager.nix`](https://github.com/NotAShelf/nvf/blob/main/flake/modules/home-manager.nix) at [lines 57-78](https://github.com/NotAShelf/nvf/blob/8ff50562d7203a2b87bc6409e806f13b115d6b48/flake/modules/home-manager.nix#L57C1-L78C5).

It is also noted in the [documentation](https://notashelf.github.io/nvf/index.xhtml#ch-hm-module) (accessible on the README).

Good luck with Nix, brotha.

**Comment by NotAShelf** [comment]
The packages exposed by the flake (i.e. those you can `nix run`) are configured [here](https://github.com/NotAShelf/nvf/blob/main/configuration.nix). You can copy all options that are set to `true` in order to replicate the default configuration.

**Comment by cratedev** [comment]
> The packages exposed by the flake (i.e. those you can `nix run`) are configured [here](https://github.com/NotAShelf/nvf/blob/main/configuration.nix). You can copy all options that are set to `true` in order to replicate the default configuration.

Well I'm a fool. I looked at that, but saw "isMaximal" at the beginning and assumed that wasn't what I was after. Thanks!
