### ISSUE TITLE
Fails to build on NixOS

### ISSUE THREAD

**Issue by AlephNought0** [NotAShelf/nvf#441]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

After updating my flake today nvf fails to build.  Here's my config for the nvf https://github.com/AlephNought0/Faery/blob/main/modules/home/programs/graphical/nvf/default.nix

### 👟 Reproduction steps

1. Have my system in which nothing seems to be working I guess
2. Update the flake
3. Build
4. Epic fail

### 👀 Expected behavior

nvf building successfuly

### 😓 Actual Behavior

nvf building unsuccesfuly

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.11.5-cachyos, NixOS, 24.11 (Vicuna), 24.11.20241029.807e915`

### 📝 Relevant log output

```bash
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/6rnnj6d0sbn4wq8wyvbiscw3kx3j7ilk-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
applying patch /nix/store/ndjbnla2z91svc03yyll0q8pxphp77x2-fix-cross-mingw-build.patch
patching file C/7zip_gcc_c.mak
patching file C/7zVersion.rc
patching file C/Util/7zipInstall/resource.rc
patching file C/Util/7zipInstall/resource.rc.rej
patching file C/Util/7zipUninstall/resource.rc
patching file C/Util/7zipUninstall/resource.rc.rej
patching file CPP/7zip/7zip_gcc.mak
patching file CPP/7zip/Crypto/RandGen.cpp
patching file CPP/7zip/GuiCommon.rc
patching file CPP/7zip/UI/FileManager/PanelItemOpen.cpp
patching file CPP/7zip/UI/FileManager/SysIconUtils.h
patching file CPP/Windows/Control/ComboBox.h
patching file CPP/Windows/Control/ImageList.h
patching file CPP/Windows/Control/ListView.h
patching file CPP/Windows/Control/ProgressBar.h
patching file CPP/Windows/SecurityUtils.h
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: -j16 SHELL=/nix/store/mm0pa3z7kk6jh1i9rkxqxjqmd8h1qpxf-bash-5.2p37/bin/bash CC=cc CXX=c++ DISABLE_RAR_COMPRESS=true
mkdir -p b/g_x64
asmc -nologo -elf64 -DABI_LINUX -Fob/g_x64/ ../../../../Asm/x86/LzmaDecOpt.asm
/nix/store/mm0pa3z7kk6jh1i9rkxqxjqmd8h1qpxf-bash-5.2p37/bin/bash: line 1: asmc: command not found
make: *** [../../7zip_gcc.mak:1310: b/g_x64/LzmaDecOpt.o] Error 127
```

**Comment by AlephNought0** [comment]
After trying multiple things such as commenting out my extra plugin, changing neovim package and unfollowing nixpkgs on nvf flake it still fails to build.

**Comment by C4E5G3** [comment]
#!/usr/bin/env bash
 for bash files in Nixos

**Comment by AlephNought0** [comment]
> #!/usr/bin/env bash for bash files in Nixos

I am not modifying source code of nvf in any way so I am not sure how could that help. I am aware that bash error is outputted in the log but I don't think that's the main culprit.

**Comment by C4E5G3** [comment]
If it is a flake you just nix run or nix build it

**Comment by NotAShelf** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/353553

Looks like the lockfile on `main` is affected, and so is your configuration. Current options are to either wait, or create an overlay to propagate the fixes to your system before it's in your channel (give or take 3~ days).

**Comment by NotAShelf** [comment]
The fix is now in unstable channel, closing.
