### ISSUE TITLE
FAQ in README cut off mid sentence

### ISSUE THREAD

**Issue by kimjongbing** [NotAShelf/nvf#479]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

In the FAQ of the README, one of the sentences is just cut-off mid sentence.
![image](https://github.com/user-attachments/assets/9f5e4631-f5ea-4e51-ad72-3142feabd0f2)

Not a technical problem or anything but I don't know what it's telling me to look at

### 👟 Reproduction steps

Real eyes realize real lies

### 👀 Expected behavior

Sentence to finish

### 😓 Actual Behavior

Sentence does not finish

### 💻 Metadata

Not relevant

### 📝 Relevant log output

```bash
Not relevant
```

**Comment by NotAShelf** [comment]
If I didn't have the attention span of a field rat, itwould tell you to "take a look *at the manual*" and give you a link.

I'm sorry this has gone unfixed for too long, it has been fixed in the current indev branch (`v0.7`), which we are hoping to release very soon. I

**Comment by kimjongbing** [comment]
> If I didn't have the attention span of a field rat, itwould tell you to "take a look _at the manual_" and give you a link.
> 
> I'm sorry this has gone unfixed for too long, it has been fixed in the current indev branch (`v0.7`), which we are hoping to release very soon. I

i see what you did there lol

**Comment by NotAShelf** [comment]
:)

**Comment by NotAShelf** [comment]
I could probably backport the change, actually.
