### ISSUE TITLE
Setting mappings to null doesn't diable them

### ISSUE THREAD

**Issue by upidapi** [NotAShelf/nvf#484]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

Before (i assume) the v0.7 merge setting a mapping (vim.debugger.nvim-dap.mappings.restart = null) would result in it not being set. However now it causes an error, probably due to the mapping rewrite. 

### 👟 Reproduction steps

set "vim.debugger.nvim-dap.mappings.restart = null"
build

### 👀 Expected behavior

It doesn't set the binding

### 😓 Actual Behavior

It crashes 

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.6.63, NixOS, 25.05 (Warbler), 25.05.20241201.ac35b10`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.24.10`  - nixpkgs: `/nix/store/ab78nf3ad8ly49zfyd3igw3f2n5q7fz4-source`

### 📝 Relevant log output

```bash
error: A definition for option `vim.keymaps."[definition 1-entry 2]".key' is not of type `string'. Definition values:
       - In `/nix/store/kalwrqa2q06cvh813xifqcx78d4mzkqi-source/modules/plugins/debugger/nvim-dap/config.nix': null
```

**Comment by horriblename** [comment]
can you try out #485?

**Comment by upidapi** [comment]
Seems to work, although the keybinds are still set, but that is probably due to something in my config. Thanks
